export const actionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  SET_DATA: "SET_DATA",
  CALCULATE_FINAL_PRICE: "CALCULATE_FINAL_PRICE",
  ADD_QUANTITY:"ADD_QUANTITY"
};
